# Generated by Django 4.2.7 on 2023-11-20 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TemplateConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Django Shorten URLs", max_length=50),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="logo/", verbose_name="Logo"
                    ),
                ),
                (
                    "manual_book",
                    models.URLField(
                        blank=True, null=True, verbose_name="Link Manual Book"
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Configuration",
            },
        ),
    ]
